// Evaluator-owned synthetic records. Student agents must discover these only
// through rendered browser pages, never by reading this module or control files.
export const primarySources = {
  nasa: {title:'NASA: Evidence for climate change',url:'https://science.nasa.gov/climate-change/evidence/'},
  loc: {title:'Library of Congress: Drafting the Declaration of Independence',url:'https://www.loc.gov/exhibits/declara/declara4.html'},
};
export const drafts = {
  climate: {
    title:'Avery’s climate evidence draft',
    paragraphs:[
      'A cold afternoon does not disprove climate change. Weather describes conditions over a short period, while climate describes patterns observed over longer periods. My main claim is that several kinds of measurements together provide stronger evidence of a warming climate than one temperature record alone. However, I have not yet identified exactly which time periods each measurement covers, so my comparisons below need to be made more precise.',
      'NASA’s evidence page discusses temperature, oceans, ice and sea level. I think these observations should be considered together because different instruments observe different parts of the Earth system. A thermometer on land does not measure the same thing as a satellite observing ice. If both observations change in ways consistent with warming, agreement between them matters. In my current draft I call this independent confirmation, but I need to explain what limitations the observations share rather than assuming that they are completely independent.',
      'The first example is global surface temperature. I wrote in my outline that every place on Earth gets warmer every year. That sentence seems too strong: an average can rise while an individual place or year is cooler. I need to replace it with a statement about the actual global record and its period of measurement. I also wrote that the planet has warmed by five degrees since 2000, but I do not have a source for that number. It should not remain in my final paper unless a reliable source supports it, including a unit and baseline.',
      'The second example is sea level. Warmer water occupies more space, and melting ice on land can contribute water to the ocean. These are different mechanisms, and I should explain both. My rough notes accidentally say that all floating sea ice melting must raise sea level by its full volume. I have not checked that claim. This is a place where an explanation of the physical mechanism would be better than listing a dramatic result. I also need to distinguish global average sea level from local flooding, which can be affected by land movement and other factors.',
      'One possible counterargument is that climate has changed naturally before, so current warming must also be natural. Historical change shows that climate responds to influences; it does not by itself identify the causes of the present trend. My response needs evidence about the present influences and should not say that natural causes never matter. I have not yet separated an evidence-of-change claim from an attribution-of-cause claim. The assignment asks for the former, so I should make the distinction explicit.',
      'In conclusion, a stronger paper will compare two clearly sourced indicators, describe what each measures, state the period and uncertainty, and explain why agreement matters. My current reference list only says NASA website. I need the page title, exact link, and access date, and I need citations beside specific facts. I would like feedback on my reasoning and an ordered revision checklist. Please preserve my words where they work instead of rewriting the entire submission for me.',
    ],
  },
  history: {
    title:'Jordan’s Declaration argument draft',
    paragraphs:[
      'The Declaration of Independence was an argument intended to persuade readers that separation from Britain was justified. My claim is that the document connects general principles about government to complaints about the king. Those two parts have different jobs: one sets a standard for legitimate government, and the other tries to show that the standard has been violated. I need to show this connection with specific passages instead of saying only that the document was important.',
      'In my first paragraph I say that Thomas Jefferson wrote the complete final version entirely by himself. The Library of Congress page describes a rough draft and changes by other people, so this claim needs correction. The existence of revisions could help my argument because it shows that the wording was debated. I need to distinguish the person who prepared an early draft from the committee and Congress who reviewed the language. I also need to check the difference between adoption and signing dates instead of treating every event as July fourth.',
      'The phrase about consent of the governed suggests that political authority should come from the people. I currently explain this as a promise that every person immediately received an equal vote in 1776. That seems to confuse an asserted principle with how political rights actually worked. My draft needs a more careful claim about the principle, and a separate acknowledgment of people who were excluded. I should support any claim about those exclusions with an appropriate source rather than guessing what every signer believed.',
      'A list of grievances follows the broad principles. Instead of copying a long list, I want to choose one complaint and explain how it illustrates the argument about legitimate government. Right now my paragraph says the king did bad things, which is too vague to evaluate. A stronger paragraph would identify the complaint, explain the behavior being criticized, and connect it to the document’s stated standard. It should also make clear that I am analyzing the authors’ argument, not assuming that every claim in a political document is automatically neutral evidence.',
      'The audience might include colonists who were uncertain about independence and readers outside the colonies. I have not supported this audience claim yet. The opening explanation about giving reasons could be relevant, but I need to quote or paraphrase a specific passage and explain why it supports my interpretation. I should avoid saying that all people in the colonies agreed. A persuasive document can reveal what its authors want readers to accept without proving that every reader accepted it.',
      'My conclusion currently repeats that the Declaration was important. I can improve it by returning to my claim about principles and grievances and showing what my selected example demonstrates. My source list says Library of Congress without a document title or link. Before submitting I need two short pieces of textual evidence, an explanation after each, precise dates where relevant, and a complete citation. I want detailed feedback tied to this draft and the rubric, not a new essay to hand in.',
    ],
  },
};
const task=(id,title,due,extra={})=>({id,title,due,required:true,status:'Not submitted',...extra});
const grade=(title,score,possible,category)=>({title,score,possible,category});
export const students = {
  college:{name:'Avery Fixture',email:'avery@example.edu',school:'Example University',level:'college',term:'Fall 2026',timezone:'America/New_York',provider:'Brightspace by D2L',courses:[
    {id:'college-bio201',name:'BIO201 Biology Laboratory',instructor:'Dr. Rivera',officeHours:'Wednesday 2–3 PM Eastern, Science 204',weights:[['Labs',50],['Quizzes',20],['Final',30]],grades:[grade('Practice lab',18,25,'Labs'),grade('Safety quiz',7,10,'Quizzes')],tasks:[task('college-lab-1','Lab 1 methods and evidence','2026-09-11T23:59:00-04:00',{correction:true,rubric:'Methods 40 points: replicable procedure and control variables. Evidence 40 points: label observations and distinguish them from interpretation. Clarity 20 points: organized report with units and source citations.'}),task('college-lab-quiz','Quiz 1','next Friday (reference date not supplied)'),task('college-bio-orientation','Lab orientation','2026-09-08',{status:'Submitted; complete',required:true})]},
    {id:'college-env150',name:'ENV150 Climate and Evidence',instructor:'Professor Chen',officeHours:'Monday 11 AM–noon Eastern, by appointment',weights:[['Papers',50],['Participation',20],['Final',30]],grades:[grade('Source comparison',12,15,'Papers'),grade('Discussion 1',8,10,'Participation')],research:'nasa',draft:'climate',tasks:[task('college-climate-paper','Climate evidence paper draft','2026-09-16',{draft:'climate',rubric:'Claim and reasoning 30 points: state a qualified claim and explain mechanisms. Evidence 35 points: use at least two indicators, correct units/baselines and specific citations. Counterargument 20 points: answer a plausible objection without overstating certainty. Organization and attribution 15 points: clear paragraphs and complete source details.'}),task('college-extra-seminar','Optional climate seminar reflection','2026-09-18T17:00:00-04:00',{required:false})]},
    {id:'college-eng102',name:'ENG102 Academic Writing',instructor:'Professor Singh',officeHours:'Thursday 1–2 PM Eastern',weights:[['Essays',60],['Workshops',20],['Final',20]],gradesHidden:true,tasks:[task('college-reading','Reading response','2026-09-17'),task('college-peer-review','Peer review meeting','2026-09-18T10:00:00-04:00')]},
  ]},
  'high-school':{name:'Jordan Fixture',email:'jordan@example.edu',school:'Example High School',level:'high-school',term:'Fall 2026',timezone:'America/New_York',provider:'Google Classroom',courses:[
    {id:'hs-algebra2',name:'Algebra II',instructor:'Ms. Patel',officeHours:'Tuesday lunch, Room 12',weights:[['Homework',30],['Quizzes',30],['Tests',40]],grades:[grade('Linear review',17,20,'Homework'),grade('Quiz 1',6,8,'Quizzes')],tasks:[task('hs-equations','Systems of equations practice','2026-09-11T17:00:00-04:00',{rubric:'Method 50 points: show each algebraic step. Accuracy 30 points: check both variables in the original equations. Explanation 20 points: explain why a solution satisfies both equations.'}),task('hs-math-extension','Optional challenge problem','2026-09-13',{required:false}),task('hs-math-orientation','Math orientation','2026-09-08',{status:'Submitted; complete'})]},
    {id:'hs-history10',name:'US History',instructor:'Mr. Brooks',officeHours:'Wednesday after school, Room 18',weights:[['Essays',60],['Coursework',20],['Final',20]],grades:[grade('Source analysis',16,20,'Essays'),grade('Reading notes',8,10,'Coursework')],research:'loc',draft:'history',tasks:[task('hs-declaration','Declaration argument draft','2026-09-14T23:59:00-04:00',{correction:true,draft:'history',rubric:'Argument 25 points: focused defensible claim about principles and grievances. Primary evidence 30 points: two accurately contextualized textual examples. Reasoning and historical accuracy 30 points: explain each example, distinguish draft/adoption/signing and ideals/practice. Citation and organization 15 points: complete source identification and coherent paragraphs.'}),task('hs-history-reading','Historical context reading','2026-09-15')]},
    {id:'hs-science10',name:'Earth Science',instructor:'Ms. Gomez',officeHours:'Friday lunch, Lab 3',weights:[['Labs',45],['Quizzes',25],['Final',30]],gradesHidden:true,research:'nasa',tasks:[task('hs-science-quiz','Climate vocabulary quiz','next Friday (reference date not supplied)'),task('hs-weather-log','Weather observation log','2026-09-17T08:15:00-04:00')]},
  ]},
};
